"""Add BeautyResult model for caching beauty analysis results

Revision ID: 76765e1e23b4
Revises: e542d1ccefac
Create Date: 2025-09-15 13:45:47.908268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76765e1e23b4'
down_revision = 'e542d1ccefac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beauty_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('beauty_ratings', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('category_scores', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beauty_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beauty_results_image_hash'), ['image_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beauty_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beauty_results_image_hash'))

    op.drop_table('beauty_results')
    # ### end Alembic commands ###
