"""Add validation fields to BeautyResult model

Revision ID: 9d54f3f7e54e
Revises: 76765e1e23b4
Create Date: 2025-09-15 14:07:54.702733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d54f3f7e54e'
down_revision = '76765e1e23b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beauty_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_result', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('validation_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_valid_camel', sa.Boolean(), nullable=True))
        batch_op.alter_column('beauty_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beauty_results', schema=None) as batch_op:
        batch_op.alter_column('beauty_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('is_valid_camel')
        batch_op.drop_column('validation_error')
        batch_op.drop_column('validation_result')

    # ### end Alembic commands ###
