"""add_prompt_field_to_conversation_model

Revision ID: afb42dcbdb21
Revises: a0b3ff6d0862
Create Date: 2025-09-18 17:02:49.301446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb42dcbdb21'
down_revision = 'a0b3ff6d0862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
